name: Terraform

on:
  push:
    branches: ["main"]

jobs:
  plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Terraform

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v4
        with:
          cli_config_credentials_token: ${{ secrets.TERRAFORM_API_TOKEN }}
          terraform_version: "1.15.8"

      - run: terraform init

      - id: plan
        run: terraform plan -no-color

      - name: Show Plan Output
        if: always()
        env:
          PLAN_STDOUT: ${{ steps.plan.outputs.stdout }}
          PLAN_STDERR: ${{ steps.plan.outputs.stderr }}
          PLAN_EXITCODE: ${{ steps.plan.outputs.exitcode }}
        run: |
          echo "Exit Code: $PLAN_EXITCODE"
          echo "=== STDOUT ==="
          echo "$PLAN_STDOUT"
          echo "=== STDERR ==="
          echo "$PLAN_STDERR"
